version: "1.0 "
services:
  service:
    container_name: service
    image: gb_service
    environment:
      - CONFIG_PATH=
    ports:
      - "3000:3000"
    depends_on:
      - nginx
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 4000:5432
    environment:
      - POSTGRES_PASSWORD=1787
      - POSTGRES_DB=db
      - POSTGRES_USER=admin

  nginx:
    image: nginx
    container_name: proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
